import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class GroupInfo extends javax.swing.JFrame {

    /**
     * Creates new form GroupInfo
     */
    
    private ChatWindow MyChatWindow;
    private ArrayList<String> selectedList;
    private ArrayList<String> NotInGroupList;
    private ArrayList<String> deletedMembersList;
    
    String[] groupNames;
    String adminN, groupN;
    //private static String[] OnPeople = {"sameh","fady","mark","rizk","reem","raymon"};
    
    
   // ArrayList<String> list = new ArrayList<String>(Arrays.asList(OnlineList.selected));
    //ArrayList<String> list2 = new ArrayList<String>(Arrays.asList(OnlineList.NotInGroup));
    
    public GroupInfo(ChatWindow c) {
        
        selectedList = c.getGroupChatSelectedList();
        NotInGroupList = c.getGroupChatNotSelectedList();
        
        MyChatWindow = c;
        
        initComponents();
        adminN = selectedList.get(0);
        
        if(c.getGroupFlag() == 1)
        {
            adminN = Main.username;
            editButton.setVisible(true);
            deleteButton.setVisible(true);
        }
        else
        {
            editButton.setVisible(false);
            deleteButton.setVisible(false);
        }
        groupName.setText(MyChatWindow.getId());
        adminName.setText(adminN);
        
        membersList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        membersList.setListData(removeUserFromPreview(selectedList).toArray(new String[removeUserFromPreview(selectedList).size()]));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        membersList = new javax.swing.JList<String>();
        deleteButton = new javax.swing.JButton();

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        groupName.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        groupName.setText("[Group Name]");

        jLabel2.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel2.setText("Created by: ");

        adminName.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        adminName.setText("[Admin Name]");

        jLabel4.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel4.setText("Members:");

        editButton.setLabel("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        membersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(membersList);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(groupName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adminName)
                                .addGap(0, 58, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(deleteButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(adminName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

        EditGroup eg = new EditGroup(MyChatWindow);
        eg.setVisible(true);

    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        //    list = OnlineList.selectedList;
          //  list2 = OnlineList.Notgrp;
            int temp[]= membersList.getSelectedIndices();
        
            if(temp.length != 0)
            {
               deletedMembersList = new ArrayList<String>();
            
//            if(temp.length < OnlineList.selectedList.size())
//            {
                for(int i=0;i<temp.length;i++)
                {
                   NotInGroupList.add(selectedList.get(temp[i]));
                   deletedMembersList.add(selectedList.get(temp[i]));
                }
                Iterator<String> it = selectedList.iterator();
                while(it.hasNext())
                {
                    if(NotInGroupList.contains(it.next()))
                        it.remove();
                }
                membersList.setListData(removeUserFromPreview(selectedList).toArray(new String[(removeUserFromPreview(selectedList).size())]));
                MyChatWindow.setGroupChatSelectedList(selectedList);
                MyChatWindow.setGroupChatNotSelectedList(NotInGroupList);
                OnlineList.Sconnect.removeUser(deletedMembersList.toArray(new String[(deletedMembersList.size())]), MyChatWindow.getId());
            }
            else
            {
                JOptionPane.showMessageDialog(null,"please choose a member to remove!");
            }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
          membersList.setListData(removeUserFromPreview(MyChatWindow.getGroupChatSelectedList()).toArray(new String[removeUserFromPreview(selectedList).size()]));
    }//GEN-LAST:event_formWindowGainedFocus

    private ArrayList<String> removeUserFromPreview(ArrayList<String> p)
    {
        ArrayList<String> previewList = p;
        for(int i =0; i < p.size(); i++ )
        {
            if(p.get(i).equals(Main.username))
                previewList.remove(i);
        }
        return previewList;
    }
    
    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminName;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel groupName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> membersList;
    // End of variables declaration//GEN-END:variables
}
