import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class WelcomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public static ServerConnection mainServer;
       
    public WelcomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeScreenPane = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        UsernameLable = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        Aboutus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        Title.setText("CSE Chat");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        UsernameLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UsernameLable.setText("Username");

        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        LoginBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        Aboutus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Aboutus.setText("About Us");
        Aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutusMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AboutusMousePressed(evt);
            }
        });

        javax.swing.GroupLayout WelcomeScreenPaneLayout = new javax.swing.GroupLayout(WelcomeScreenPane);
        WelcomeScreenPane.setLayout(WelcomeScreenPaneLayout);
        WelcomeScreenPaneLayout.setHorizontalGroup(
            WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                .addGroup(WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo)
                        .addGap(18, 18, 18)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(UsernameLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(159, 159, 159))
            .addGroup(WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                    .addGap(503, 503, 503)
                    .addComponent(Aboutus)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        WelcomeScreenPaneLayout.setVerticalGroup(
            WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                .addGroup(WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLable)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(WelcomeScreenPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WelcomeScreenPaneLayout.createSequentialGroup()
                    .addContainerGap(311, Short.MAX_VALUE)
                    .addComponent(Aboutus)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WelcomeScreenPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WelcomeScreenPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
      
         if(UsernameTextField.getText().equals(""))
             JOptionPane.showMessageDialog(null,"please enter your username");
         else
         {
                Main.username=UsernameTextField.getText();
                //send user name to server and get online list
               //ClientServerSocket c;
//                java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               
//            }
//        });
                
                
                 new Thread(
            new Runnable() {
                public void run() {
                  try {
              mainServer=new ServerConnection(Main.MainServerIp,Main.MainServerPort);
              mainServer.start();
              
          } catch (IOException ex) {
              Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
          }
                }
            }
        ).start();
            
             //JOptionPane.showMessageDialog(null, username);
                 dispose();
         }
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void AboutusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AboutusMousePressed

    private void AboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutusMouseClicked
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUs().setVisible(true);
            }
        });
    }//GEN-LAST:event_AboutusMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aboutus;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UsernameLable;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JPanel WelcomeScreenPane;
    // End of variables declaration//GEN-END:variables
}
